// import { useEffect, useRef } from 'react';
// import Head from 'next/head';
// import styles from '@/styles/Home.module.css';
// import Header from '@/components/Header';
// import ScrollSection from '@/components/ScrollSection';
// import { ScrollTrigger } from 'gsap-trial/dist/ScrollTrigger';
// import { ScrollSmoother } from 'gsap-trial/dist/ScrollSmoother';
// import { gsap } from 'gsap';


// export default function Home() {
//   const smoother = useRef()

//   const scrollTo = () => {
//     smoother.current.scrollTo('.box-c', true, 'center center');
//   };


//   useEffect(() => {
//     // if (!sessionStorage.getItem('animationPlayed')) {
//     //   // Run the animation
//     //   gsap.fromTo('.animated-text',
//     //     { opacity: 0, y: -50 },
//     //     {
//     //       opacity: 1, y: 0, duration: 1, onComplete: () => {
//     //         // Hide the fullscreen overlay after the animation ends
//     //         gsap.to('.fullscreen-overlay', {
//     //           opacity: 0, duration: 1, onComplete: () => {
//     //             document.querySelector('.fullscreen-overlay').style.display = 'none';
//     //           }
//     //         });
//     //         // Set a flag to indicate the animation has run
//     //         sessionStorage.setItem('animationPlayed', 'true');
//     //       }
//     //     }
//     //   );
//     // } else {
//     //   // Hide the overlay immediately if the animation has already run
//     //   document.querySelector('.fullscreen-overlay').style.display = 'none';
//     // }

//     // Smooth scrolling setup
//     smoother.current = ScrollSmoother.create({
//       wrapper: '#smooth-wrapper',
//       content: '#smooth-content',
//       smooth: 2,
//       effects: true,
//     });

//   }, []);




//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//         <script src="https://cdn.tailwindcss.com"></script>
//       </Head>
//       <div>
//         <Header />
//         <div id={`smooth-wrapper`}>
//           <div id="smooth-content">

//             <main className={styles.main} style={{ paddingTop: '4rem' }}>

//               {/* <div className="fullscreen-overlay">
//             <div className="animated-text">Your Text Here</div>
//             <div className="animated-text">Your Text Here</div>
//           </div> */}
//               <div className='div' />
//               <ScrollSection />
//               <div className='div' />
//             </main>
//           </div>

//         </div>

//       </div>
//     </>
//   );
// }
import { useEffect, useRef } from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Header from '@/components/Header';
import ScrollSection from '@/components/ScrollSection';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap-trial/dist/ScrollTrigger';
import { ScrollSmoother } from 'gsap-trial/dist/ScrollSmoother';
import FullScreenAnimation from '@/components/FullScreenAnimation';
import HeroSection from '@/components/Home/HeroSection';

gsap.registerPlugin(ScrollTrigger, ScrollSmoother);

export default function Home() {
  const smoother = useRef();

  useEffect(() => {
    // Check if the animation has already run
    if (!sessionStorage.getItem('animationPlayed')) {
      // Run the animation
      gsap.fromTo('.animated-text',
        { opacity: 0, y: -50 },

      );
    }

    // Smooth scrolling setup
    smoother.current = ScrollSmoother.create({
      wrapper: '#smooth-wrapper',
      content: '#smooth-content',
      smooth: 2,
      effects: true,
    });

  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <div>
        <Header />

        <div id="smooth-wrapper">

          <div id="smooth-content">
            <main className={styles.main} >
              {/* <div className="fullscreen-overlay">
                <div className="animated-text">Your Text Here</div>
                <div className="animated-text">Your Text Here</div>
              </div> */}


              <HeroSection />

              <FullScreenAnimation />
              <div className='div' />
              <div className='div2' />

              <ScrollSection />
              <div className='div' />
            </main>
          </div>
        </div>
      </div >
    </>
  );
}
