// import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";
// import Header from "../components/Header";
// import { motion } from "framer-motion";
// import HorizontalScroll from "@/components/Header/HorizontalScroll";

// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//         <script src="https://cdn.tailwindcss.com"></script>
//       </Head>
//       <main className={styles.main}>
//         <div>
//           <Header />
//           <main style={{ paddingTop: "4rem" }}>
//             <HorizontalScroll />
//           </main>
//         </div>
//       </main>
//     </>
//   );
// }

// pages/index.jsx

// pages/index.jsx
// pages/index.jsx
// +++++++
// import Head from 'next/head';
// import styles from '@/styles/Home.module.css';
// import Header from '@/components/Header';
// import HorizontalScroll from '@/HorizontalScroll';

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div>
//         <Header />
//         <main className={styles.main} style={{ paddingTop: '4rem' }}>
//           <HorizontalScroll />
//           <div className="mydiv"></div>
//         </main>
//       </div>
//     </>
//   );
// }

// +++++++

// pages/index.jsx
// import Head from 'next/head';
// import styles from '@/styles/Home.module.css';
// import Header from '@/components/Header';
// import HorizontalScroll from '@/components/HorizontalScroll';
// import StickySection from '@/components/StickySection';

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div>
//         <Header />
//         <main className={styles.main} style={{ paddingTop: '4rem' }}>
//           <StickySection />
//           <HorizontalScroll />
//           <StickySection />
//           {/* <div className="mydiv"></div> */}
//         </main>
//       </div>
//     </>
//   );
// }
// pages/index.jsx

// import Head from 'next/head';
// import styles from '@/styles/Home.module.css';
// import Header from '@/components/Header';
// import HorizontalScroll from '@/components/HorizontalScroll';
// import StickySection from '@/components/StickySection';

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div>
//         <Header />
//         <main className={styles.main} style={{ paddingTop: '4rem' }}>
//           <StickySection />
//           <HorizontalScroll />
//           <StickySection />
//           <div className="mydiv"></div>
//         </main>
//       </div>
//     </>
//   );
// }
// pages/index.jsx
// pages/index.jsx
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Header from '@/components/Header';
import HorizontalScroll from '@/components/HorizontalScroll';
import StickySection from '@/components/StickySection';
import ScrollHandler from '@/components/HorizontalScroll';
import HorizontalScroll2 from '@/components/HorizontalScroll2';
import ScrollSection from '@/components/ScrollSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>

      </Head>
      <div>
        <Header />

        <main className={styles.main} style={{ paddingTop: '4rem' }}>
          <div className='div' />
          <ScrollSection />
          <div className='div' />
        </main>
      </div>
    </>
  );
}
