
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Header from '@/components/Header';
import ScrollSection from '@/components/ScrollSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>

      </Head>
      <div>
        <Header />

        <main className={styles.main} style={{ paddingTop: '4rem' }}>
          <div className='div' />
          <ScrollSection />
          <div className='div' />
        </main>
      </div>
    </>
  );
}
